import './globals.css'

import 'tailwindcss/tailwind.css'




export const metadata = {
  title: 'Tee',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
     
    </html>
    
  )
}
